### ISSUE TITLE
Still highlight after mouse get away

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#10]
![image](https://user-images.githubusercontent.com/68589851/129061364-147e5790-0136-4755-80ef-c2c92e354813.png)
Not sure if this is intended, but it certainly looks strange.
It only changes when I click it.
![image](https://user-images.githubusercontent.com/68589851/129061498-38dd4a51-5acd-4201-8eaf-3b7a67bebea4.png)
Same in the screenshot.

**Comment by SiongSng** [comment]
此錯誤已修正，感謝回報
