### ISSUE TITLE
Strange mods listing behavior after click either world or screenshot.

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#11]
![image](https://user-images.githubusercontent.com/68589851/129061696-4987f344-5422-4833-a021-60b7f195eb75.png)
Will fix if you exit instance and then reenter

**Comment by KyleUltimate** [comment]
if you click world instead of screenshot, this will happen instead
![image](https://user-images.githubusercontent.com/68589851/129061961-38a0976c-28a7-4ceb-9e22-913e795dc556.png)
The fix is the same

**Comment by SiongSng** [comment]
現在還會有此錯誤嗎? 因為我似乎無法重現該錯誤

**Comment by KyleUltimate** [comment]
更新至最新以修復此錯誤
