### ISSUE TITLE
開啟RML會白屏(win 10)

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#117]
**描述錯誤**
開啟RML會白屏(win 10)

**重現步驟**
重現觸發這個錯誤的步驟：
1. 開啟 '最新版RPMLauncher'
2.發現錯誤:白屏

**預期行為**
開啟RML

**截圖**
![image](https://user-images.githubusercontent.com/89505079/140311983-bd4d9df4-cbf3-40c2-a0fd-41d999a3afd7.png)

**RPMLauncher 日誌
無
請將日誌檔案內的資料貼上於此處
無

*辨識資訊 (請填寫以下資訊):**
 - 作業系統: Win10
 - RPMLauncher 版本1.0.0.683

**其他說明**
要刪掉甚麼檔案嗎?

**Comment by SiongSng** [comment]
此錯誤已修復 07dc396d25490490e659e3d428c92a8baccc0758
