### ISSUE TITLE
自動關閉遊戲日誌畫面

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#120]
**您的功能請求是否與其他問題有關?**
RML無法自動關閉遊戲日誌的畫面

**描述您想要的解決方案**。
在設定中能更改

**描述你考慮過的替代方案**。
在設定中新增按鈕更改
**額外說明**
![image](https://user-images.githubusercontent.com/89505079/140323287-2ddbeaf5-ac37-486d-8a38-d9dd716f74b6.png)

**Comment by SiongSng** [comment]
你想要的是在遊戲關閉後自動關閉遊戲日誌畫面嗎？
