### ISSUE TITLE
RML頁面切畫動畫問題

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#121]
**您的功能請求是否與其他問題有關?**
RML頁面切畫動畫問題

**描述您想要的解決方案**。
無法直接滑到下一頁

**描述你考慮過的替代方案**。
無

**額外說明**
https://user-images.githubusercontent.com/89505079/140590078-e3ebcfeb-513e-430c-a234-9996308b2d5c.mp4

**Comment by SiongSng** [comment]
影片檔案資訊不完整
