### ISSUE TITLE
指到圖案顯示文字的速度問題

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#125]
**描述錯誤**
指到圖案顯示文字的速度問題
**重現步驟**
重現觸發這個錯誤的步驟：
( 範例 ):
1. 指到圖示時，資訊顯示太快。
![image](https://user-images.githubusercontent.com/89505079/140603566-8585e83d-1cf4-49d7-b412-91607e997d53.png)

**預期行為**
希望能延遲0.5秒(?

**截圖**
![image](https://user-images.githubusercontent.com/89505079/140603543-ea1aac61-116a-4645-a173-46361e354c6c.png)

*辨識資訊 (請填寫以下資訊):**
 - 作業系統:win10
 - RPMLauncher 版本 696

**其他說明**
顯示正常，但過於快速，希望能改善。(眼花

**Comment by SiongSng** [comment]
此應該為改進而不是錯誤
