### ISSUE TITLE
讓模組名稱可以被反白選取

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/RPMLauncher#127]
**您的功能請求是否與其他問題有關?**
在自行更新模組的時候，模組名稱不能被反白選取，有點麻煩

**描述您想要的解決方案**。
可以讓模組名稱可以被反白選取

**描述你考慮過的替代方案**。
無

**額外說明**
![image](https://user-images.githubusercontent.com/76562059/140605275-e6a6f8eb-a5cc-4f54-849c-7f90c64bc4c2.png)

**Comment by sunny0531** [comment]
You should be able to highlight select text at next release
