### ISSUE TITLE
模組介面，刪除模組的時候，會卡一下

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/RPMLauncher#128]
**您的功能請求是否與其他問題有關?**
在模組介面刪除模組時，會卡一下

**描述您想要的解決方案**。
可以在刪除模組的時候，可以順暢，不要卡頓

**描述你考慮過的替代方案**。
無

**額外說明**
在此加入關於該功能請求的其他說明或截圖。

**Comment by SiongSng** [comment]
()[https://cdn.discordapp.com/attachments/886451134389178369/907632818136416287/RPMLauncher_-_2021-11-09_22-06-35_Trim.mp4]
