### ISSUE TITLE
無法用滾輪滑動頁面，只能滑動滾動條來上下移動

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#130]
**描述錯誤**
無法用滾輪滑動頁面，只能滑動滾動條來上下移動

**重現步驟**
重現觸發這個錯誤的步驟：
( 範例 ):
1.用滑鼠滾輪滑動

**預期行為**
頁面向下，但卻切到下一頁
**截圖**
https://user-images.githubusercontent.com/89505079/140612590-1e19c17d-8129-48c0-bd4b-b18d3cf69613.mp4

*辨識資訊 (請填寫以下資訊):**
 - 作業系統: win10
 - RPMLauncher 版本 1.0.0+720

**其他說明**
(補充說明:滾動條還是有問題

**Comment by SiongSng** [comment]
這沒有問題 你要在中間的區域滾動
