### ISSUE TITLE
根據玩家設定的更新頻道，偵測到有更新在上方導航列新增更新提示

### ISSUE THREAD

**Issue by Cjhcr** [RPMTW/RPMLauncher#131]
**您的功能請求是否與其他問題有關?**
希望能顯示更新，提醒玩家更新較正式的版本。

**描述您想要的解決方案**。
增加圖示，用來更新RML

**描述你考慮過的替代方案**。
無

**額外說明**
![image](https://user-images.githubusercontent.com/89505079/140612780-815b1977-bbef-4349-a827-6ab616b57829.png)

**Comment by SiongSng** [comment]
更新提示是指更新穩定版？
