### ISSUE TITLE
在每個視窗新增 問題反饋 功能

### ISSUE THREAD

**Issue by FlySky-ovo** [RPMTW/RPMLauncher#175]
**您的功能請求是否與其他問題有關？**
當 有東東想要反饋 時，我 想要直接用內置的功能。

**描述您想要的解決方案**
在每個視窗都有 *問題反饋* 的功能

**描述你考慮過的替代方案**
來github上面反饋

**額外說明**
![image](https://user-images.githubusercontent.com/72594971/144599217-b1cb0fec-2937-4e8b-860a-70fd990d4804.png)

**Comment by SiongSng** [comment]
請使用 Ctrl + F 快捷鍵
