### ISSUE TITLE
There is no icon for the mods even though there should be

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#20]
![image](https://user-images.githubusercontent.com/68589851/129233241-56a9e7f8-5dfc-4468-b925-4b5bdf872720.png)

**Comment by SiongSng** [comment]
幫我檢查一下你的系統 Temp 快取資料夾裡面的 RPMLauncher_Icon 資料夾有沒有東西

**Comment by KyleUltimate** [comment]
只有4個，但都還是沒有顯示
[image: image.png]v

菘菘 ***@***.***> 於 2021年8月13日 週五 上午9:56寫道：

**Comment by SiongSng** [comment]
那你嘗試刪除系統的 home/.config/RPMLauncher/mod_index 的模組索引檔案測試看看

**Comment by KyleUltimate** [comment]
成功了，謝謝
