### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by starchaos** [RPMTW/RPMLauncher#201]
### 描述錯誤

更新成版本: 1.0.6+858 後出現的錯誤視窗，作業系統是win7 X64

![unknown](https://user-images.githubusercontent.com/37036658/146847046-113c32f2-2e8b-48eb-ab78-d944c4adaadd.png)

上網搜尋之後發現 api-ms-win-shcore-scaling-l1-1-1.dll 這個檔案要WIN8以上才有

### 重現步驟

```bash
1.更新成版本: 1.0.6+858
2.點開程式
3.出現錯誤視窗
```

### 預期行為

win7 X64 可使用

### RPMLauncher 版本

穩定版: 1.0.6+858

### 您的作業系統是？

Windows 7/8

### RPMLauncher 日誌

```shell
因程式無法開啟 故無logs
```

**Comment by SiongSng** [comment]
RPMLauncher 將不打算繼續維護支援 Windows 7，請更新至Windows 10即可解決（免費更新）

**Comment by SiongSng** [comment]
現已修復 https://github.com/RPMTW/RPMLauncher/commit/3ef67d681bdfbf3dd722890752cb9f903f4c9410
