### ISSUE TITLE
[Bug]: 啟動器更新之後，無法在 Windows 7 系統上執行

### ISSUE THREAD

**Issue by YutaYamamoto212** [RPMTW/RPMLauncher#203]
### 描述錯誤

將啟動器更新到 1.0.6+858 版本 (最新版穩定版) 之後，在 Windows 7 系統中開啟啟動器，會出現以下的錯誤訊息:
```
---------------------------
rpmlauncher.exe - 系統錯誤
---------------------------
無法啟動程式，因為您的電腦遺失 api-ms-win-shcore-scaling-l1-1-1.dll。請嘗試重新安裝以修正這個問題。 
---------------------------
確定   
---------------------------
```
這會導致 Windows 7 使用者無法執行，因為它會去調用僅存在於 Windows 8 及之後的系統的 `api-ms-win-shcore-scaling-l1-1-1.dll` 檔案。
已知可以正常執行的最新穩定版為 1.0.5+830，最新開發版為 1.0.5+847。

### 重現步驟

```bash
1. 使用 Windows 7 系統，並確保已經更新到最新，且有安裝 .NET Framework 及各個 Visual C++ Redistributable 套件並確保已經更新到最新。
2. 到官網 https://www.rpmtw.com/RWL 下載最新的穩定版啟動器。
3. 執行安裝程式。
4. 開啟啟動器，結果: 
"無法啟動程式，因為您的電腦遺失 api-ms-win-shcore-scaling-l1-1-1.dll。請嘗試重新安裝以修正這個問題。"
```

### 預期行為

可以正常開啟啟動器

### RPMLauncher 版本

1.0.6+858

### 您的作業系統是？

Windows 7/8

### RPMLauncher 日誌

```shell
* 連啟動器都無法開啟，當然沒有日誌可以提供 *
```

**Comment by SiongSng** [comment]
RPMLauncher 將不打算繼續維護支援 Windows 7，請更新至Windows 10即可解決（免費更新）

**Comment by SiongSng** [comment]
現已修復 https://github.com/RPMTW/RPMLauncher/commit/3ef67d681bdfbf3dd722890752cb9f903f4c9410
