### ISSUE TITLE
[Feature Request]: RWL's 自動更新程式 更新完成後自動重啟RWL

### ISSUE THREAD

**Issue by FlySky-ovo** [RPMTW/RPMLauncher#206]
### 描述請求

就...更新完後自動開啟RWL
不確定算 Bug 還是 Feature
因為最後一個畫面有顯示文字`正在開啟程式`
但並沒有開啟

**Comment by SiongSng** [comment]
很抱歉這屬於安裝程式的問題，我無法修正
