### ISSUE TITLE
commit 92ee737 still doesn't work

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#21]
![image](https://user-images.githubusercontent.com/68589851/129233501-2ada12c8-fc2a-4f5f-a342-3958c4ed63c9.png)
I'm positive that these mods are on curse forge

**Comment by SiongSng** [comment]
你要先點開模組的敘述才會看到

**Comment by KyleUltimate** [comment]
![image](https://user-images.githubusercontent.com/68589851/129328909-2151e962-a08e-4819-891f-cd6f602120ac.png)
![image](https://user-images.githubusercontent.com/68589851/129328921-818818f1-bd34-4fb2-a0df-59e0a10184cc.png)
![image](https://user-images.githubusercontent.com/68589851/129328943-45ecb7aa-0f50-4440-b438-439e87f12d7d.png)
is this what I suppose to do?
@SiongSng

**Comment by SiongSng** [comment]
你有更新到最新版本嗎?

**Comment by KyleUltimate** [comment]
yes
