### ISSUE TITLE
Make things actually be ocd compatabile

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#22]
![image](https://user-images.githubusercontent.com/68589851/129234361-03a672f7-f933-4032-a4ac-cfe29d92bc78.png)
make java path's outline's start as the same as the down other's one
![image](https://user-images.githubusercontent.com/68589851/129235179-dea30e4d-f23a-4219-9ca7-1b86746e47ca.png)
![image](https://user-images.githubusercontent.com/68589851/129235209-56beef46-f336-4819-9168-249d0495f4b3.png)
why ars these two images' outline is blue while most of the others' outlines are white

**Comment by SiongSng** [comment]
修復完畢，感謝回報
