### ISSUE TITLE
[Feature Request]: 限制只能同時開啟一個 RPMLauncher

### ISSUE THREAD

**Issue by Yataragasus** [RPMTW/RPMLauncher#234]
### 描述請求

建議設置類似discord啟動的功能(當已啟動登入器時再次開啟登入器自動跳轉至已啟動的登入器而不是額外再開一個.

**Comment by SiongSng** [comment]
@Yataragasus 不太可能會這樣做，因為這樣會變成說無法同時開啟兩個 RPMLauncher 視窗，但是若要多開遊戲就不能了
