### ISSUE TITLE
Feature Request: When press Esc, go back to last page

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#26]
For example, when I'm on this page
![image](https://user-images.githubusercontent.com/68589851/129568302-b6517223-1fe7-473f-8ddf-05244aa17d98.png)
I can press Esc to get back to this page
![image](https://user-images.githubusercontent.com/68589851/129568325-2b445172-c662-43c6-b39e-5cb237acb992.png)

**Comment by SiongSng** [comment]
功能新增完成
