### ISSUE TITLE
Bug report: 卡在正在解析Fabric數據資料

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#36]
![image](https://user-images.githubusercontent.com/68589851/130357283-df6dcca1-6e26-4812-b914-3a94541206ee.png)
it has been like this for hours

**Comment by SiongSng** [comment]
嘗試看看再重新新增一個安裝檔? 我剛才測試一切正常

**Comment by KyleUltimate** [comment]
nope, that doesn't help

**Comment by KyleUltimate** [comment]
This error has changed to stuck on download at 99.72
