### ISSUE TITLE
The mod search page is glitched

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#5]
![image](https://user-images.githubusercontent.com/68589851/129009781-c7b9c117-bf90-4d4d-b633-ebe4080c9cef.png)
It launches the game fine.
Using btrfs file system since it says it's a filesystem exception.
After an update from 230 to 233.

**Comment by SiongSng** [comment]
第一個錯誤已修復，第二個錯誤仍在研究原因請稍後

**Comment by SiongSng** [comment]
現在應該修正了，麻煩你再測試看看 感謝

**Comment by KyleUltimate** [comment]
Fixed, everything is back to normal.
