### ISSUE TITLE
遊戲後台建議

### ISSUE THREAD

**Issue by FlySky-ovo** [RPMTW/RPMLauncher#79]
讓遊戲後台的“嚴重錯誤”改成
- 分成兩行，每行兩個字
- 全部放一行

![image](https://user-images.githubusercontent.com/72594971/136193526-ada88753-890f-466c-988e-f984345c5602.png)

**Comment by SiongSng** [comment]
關於 "全部放一行" 是什麼意思呢? 我不太懂，感謝

**Comment by SiongSng** [comment]
好的 感謝你的建議
