### ISSUE TITLE
commit 79dabda doesn't always work

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#8]
![image](https://user-images.githubusercontent.com/68589851/129059768-5ad0f2cf-69e5-4216-9d56-c565377e614c.png)
most of these are on curse forge but it doesn't have that button
maybe due to how it has been implement

**Comment by SiongSng** [comment]
這個功能之前在測試效能的時候有關閉，忘記打開XD 稍後我將開啟

**Comment by SiongSng** [comment]
https://github.com/RPMTW/RPMLauncher/commit/92ee737a1122209957fcdda6a0184b46ed3bfef3 現已新增，因此關閉此議題
