### ISSUE TITLE
if instance has been renamed, it's not possible to delete it, restarting program cause name not found issue

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#9]
![image](https://user-images.githubusercontent.com/68589851/129060627-52ec9eac-728e-4f04-8818-04d30c3d2f38.png)
it was 1.17.1 before
Then I rename it to 1.17.1 fabric
After that I press 刪除安裝檔
And that didn't work, so I figured, what happens when I press 複製安裝檔
It duplicates itself to two name not found instances
It's possible to delete the duplicate one but not possible to delete the original

**Comment by KyleUltimate** [comment]
update it's not when copying, it's when restarting

**Comment by KyleUltimate** [comment]
update, this is terminal output when clicking delete
![image](https://user-images.githubusercontent.com/68589851/129064074-12fa9f36-c107-45c1-87c2-010da60336f8.png)

**Comment by KyleUltimate** [comment]
Update, this only happens if you have things like save and mods in the folder some how

**Comment by SiongSng** [comment]
@KyleUltimate 試試看現在還會不會這樣? 感謝

**Comment by KyleUltimate** [comment]
um that didn't fix it

**Comment by SiongSng** [comment]
此錯誤是因為沒有root權限導致無法存取資料夾與RPMLauncher無關

**Comment by KyleUltimate** [comment]
can confirm, multimc can't delete it too
